# Generated by Django 2.1 on 2018-08-21 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('payGID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('tokenNumber', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('validity', models.IntegerField(default=30)),
                ('status', models.CharField(max_length=13)),
                ('payGID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blat.Product')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='payGID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blat.Product'),
        ),
    ]
