# Generated by Django 2.1 on 2018-08-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blat', '0002_auto_20180821_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='tokenID',
            field=models.CharField(default=1, max_length=15, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tokens',
            name='tokenNumber',
            field=models.CharField(max_length=15),
        ),
    ]
