# Generated by Django 2.1 on 2018-08-21 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blat', '0004_auto_20180821_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='tokens',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blat.TokenStatus'),
        ),
    ]
