# Generated by Django 2.1 on 2018-08-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blat', '0005_auto_20180821_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenstatus',
            name='id',
        ),
        migrations.AlterField(
            model_name='tokenstatus',
            name='status',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
