# Generated by Django 2.1 on 2018-08-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blat', '0006_auto_20180822_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('new', 'NEW')], default='new', max_length=6),
        ),
        migrations.DeleteModel(
            name='TokenStatus',
        ),
    ]
