# Generated by Django 2.1 on 2018-08-23 15:46

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blat', '0011_productcategory_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='county',
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=django_countries.fields.CountryField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
