# Generated by Django 2.1 on 2018-08-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blat', '0012_auto_20180823_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
