# Generated by Django 2.1 on 2018-08-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blat', '0013_supplier_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productDescription',
            field=models.TextField(null=True),
        ),
    ]
