# Generated by Django 2.1 on 2018-08-24 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blat', '0015_bucketlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bucketlist',
        ),
    ]
