# Generated by Django 2.1 on 2018-08-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blat', '0016_delete_bucketlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='sequency',
            field=models.CharField(choices=[('Token24', 'Token 24'), ('Token45', 'Token 45'), ('Token3', 'Token 3'), ('Token35', 'Token 35'), ('Token38', 'Token 38'), ('Token4', 'Token 4'), ('Token41', 'Token 41'), ('Token23', 'Token 23'), ('Token44', 'Token 44'), ('Token7', 'Token 7'), ('Token25', 'Token 25'), ('Token14', 'Token 14'), ('Token16', 'Token 16'), ('Token10', 'Token 10'), ('Token42', 'Token 42'), ('Token48', 'Token 48'), ('Token2', 'Token 2'), ('Token12', 'Token 12'), ('Token29', 'Token 29'), ('Token36', 'Token 36'), ('Token30', 'Token 30'), ('Token6', 'Token 6'), ('Token8', 'Token 8'), ('Token43', 'Token 43'), ('Token31', 'Token 31'), ('Token21', 'Token 21'), ('Token32', 'Token 32'), ('Token40', 'Token 40'), ('Token19', 'Token 19'), ('Token15', 'Token 15'), ('Token13', 'Token 13'), ('Token26', 'Token 26'), ('Token47', 'Token 47'), ('Token18', 'Token 18'), ('Token20', 'Token 20'), ('Token34', 'Token 34'), ('Token37', 'Token 37'), ('Token46', 'Token 46'), ('Token17', 'Token 17'), ('Token33', 'Token 33'), ('Token27', 'Token 27'), ('Unlock', 'Unlock'), ('Token1', 'Token 1'), ('Token22', 'Token 22'), ('Token39', 'Token 39'), ('Token5', 'Token 5'), ('Token11', 'Token 11'), ('Token28', 'Token 28'), ('Token9', 'Token 9')], default='Token1', max_length=20),
        ),
    ]
