# Generated by Django 2.1 on 2018-08-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blat', '0018_auto_20180827_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='sequency',
            field=models.CharField(choices=[('Token11', 'Token 11'), ('Token22', 'Token 22'), ('Token32', 'Token 32'), ('Token37', 'Token 37'), ('Token25', 'Token 25'), ('Token15', 'Token 15'), ('Token21', 'Token 21'), ('Token30', 'Token 30'), ('Token13', 'Token 13'), ('Token43', 'Token 43'), ('Token45', 'Token 45'), ('Token16', 'Token 16'), ('Token39', 'Token 39'), ('Token17', 'Token 17'), ('Token26', 'Token 26'), ('Token29', 'Token 29'), ('Token38', 'Token 38'), ('Token4', 'Token 4'), ('Token9', 'Token 9'), ('Token40', 'Token 40'), ('Token3', 'Token 3'), ('Token23', 'Token 23'), ('Token31', 'Token 31'), ('Token34', 'Token 34'), ('Token41', 'Token 41'), ('Token48', 'Token 48'), ('Unlock', 'Unlock'), ('Token1', 'Token 1'), ('Token19', 'Token 19'), ('Token6', 'Token 6'), ('Token20', 'Token 20'), ('Token42', 'Token 42'), ('Token14', 'Token 14'), ('Token12', 'Token 12'), ('Token28', 'Token 28'), ('Token44', 'Token 44'), ('Token47', 'Token 47'), ('Token10', 'Token 10'), ('Token46', 'Token 46'), ('Token7', 'Token 7'), ('Token8', 'Token 8'), ('Token18', 'Token 18'), ('Token2', 'Token 2'), ('Token24', 'Token 24'), ('Token33', 'Token 33'), ('Token5', 'Token 5'), ('Token35', 'Token 35'), ('Token36', 'Token 36'), ('Token27', 'Token 27')], default='Token1', max_length=20),
        ),
    ]
