# Generated by Django 2.1 on 2018-08-31 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blat', '0020_auto_20180831_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='username',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tokens',
            name='sequency',
            field=models.CharField(choices=[('Token27', 'Token 27'), ('Token18', 'Token 18'), ('Token34', 'Token 34'), ('Token3', 'Token 3'), ('Token1', 'Token 1'), ('Token12', 'Token 12'), ('Token42', 'Token 42'), ('Token46', 'Token 46'), ('Token47', 'Token 47'), ('Token24', 'Token 24'), ('Token15', 'Token 15'), ('Token8', 'Token 8'), ('Token25', 'Token 25'), ('Token2', 'Token 2'), ('Token30', 'Token 30'), ('Token45', 'Token 45'), ('Token37', 'Token 37'), ('Token39', 'Token 39'), ('Token44', 'Token 44'), ('Token19', 'Token 19'), ('Token13', 'Token 13'), ('Token31', 'Token 31'), ('Token10', 'Token 10'), ('Token20', 'Token 20'), ('Token26', 'Token 26'), ('Token43', 'Token 43'), ('Token28', 'Token 28'), ('Token36', 'Token 36'), ('Unlock', 'Unlock'), ('Token11', 'Token 11'), ('Token4', 'Token 4'), ('Token5', 'Token 5'), ('Token21', 'Token 21'), ('Token29', 'Token 29'), ('Token17', 'Token 17'), ('Token22', 'Token 22'), ('Token14', 'Token 14'), ('Token33', 'Token 33'), ('Token23', 'Token 23'), ('Token48', 'Token 48'), ('Token7', 'Token 7'), ('Token6', 'Token 6'), ('Token16', 'Token 16'), ('Token38', 'Token 38'), ('Token35', 'Token 35'), ('Token32', 'Token 32'), ('Token9', 'Token 9'), ('Token41', 'Token 41'), ('Token40', 'Token 40')], default='Token1', max_length=20),
        ),
    ]
