# Generated by Django 2.1 on 2018-08-31 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blat', '0021_auto_20180831_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='activation_token',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blat.Tokens'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tokens',
            name='sequency',
            field=models.CharField(choices=[('Token3', 'Token 3'), ('Token35', 'Token 35'), ('Token7', 'Token 7'), ('Token17', 'Token 17'), ('Token26', 'Token 26'), ('Token29', 'Token 29'), ('Token36', 'Token 36'), ('Token24', 'Token 24'), ('Token27', 'Token 27'), ('Token28', 'Token 28'), ('Token39', 'Token 39'), ('Token47', 'Token 47'), ('Token14', 'Token 14'), ('Token2', 'Token 2'), ('Token18', 'Token 18'), ('Token1', 'Token 1'), ('Token13', 'Token 13'), ('Token32', 'Token 32'), ('Token37', 'Token 37'), ('Token30', 'Token 30'), ('Token31', 'Token 31'), ('Token45', 'Token 45'), ('Token48', 'Token 48'), ('Token20', 'Token 20'), ('Token11', 'Token 11'), ('Token19', 'Token 19'), ('Token25', 'Token 25'), ('Token12', 'Token 12'), ('Token33', 'Token 33'), ('Token40', 'Token 40'), ('Token38', 'Token 38'), ('Token44', 'Token 44'), ('Token46', 'Token 46'), ('Unlock', 'Unlock'), ('Token8', 'Token 8'), ('Token22', 'Token 22'), ('Token15', 'Token 15'), ('Token5', 'Token 5'), ('Token21', 'Token 21'), ('Token6', 'Token 6'), ('Token43', 'Token 43'), ('Token10', 'Token 10'), ('Token16', 'Token 16'), ('Token41', 'Token 41'), ('Token4', 'Token 4'), ('Token34', 'Token 34'), ('Token42', 'Token 42'), ('Token9', 'Token 9'), ('Token23', 'Token 23')], default='Token1', max_length=20),
        ),
    ]
